AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWSRegonition

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600

Resources:
  AWSRekognitionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: aws_rekognition/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - AmazonS3FullAccess
        - AmazonRekognitionFullAccess
      Environment:
        Variables:
          project_arn: arn:aws:rekognition:us-east-1:659440378738:project/Image_Detection/1659803008052
          model_arn: arn:aws:rekognition:us-east-1:659440378738:project/Image_Detection/version/Image_Detection.2022-08-06T21.54.26/1659803066289
          version_name: Image_Detection.2022-08-06T21.54.26
      Architectures:
        - x86_64
      Events:
        AWSRekognitionEvent:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*

  SrcBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "caltech-test-bucket-custom-labels"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AWSRekognitionFunction:
    Description: "AWS Rekognition Lambda Function ARN"
    Value: !GetAtt AWSRekognitionFunction.Arn
  AWSRekognitionFunctionIamRole:
    Description: "Implicit IAM Role created for AWS Rekognition function"
    Value: !GetAtt AWSRekognitionFunctionRole.Arn
